# k8s/daemonset-xdp.yaml (attach XDP + create maps)
#DaemonSet: XDP loader
apiVersion: apps/v1
kind: DaemonSet
metadata: { name: pcf-xdp, namespace: kube-system }
spec:
  selector: { matchLabels: { app: pcf-xdp } }
  template:
    metadata: { labels: { app: pcf-xdp } }
    spec:
      hostNetwork: true
      containers:
      - name: xdp
        image: your-registry/pcf-xdp-loader:latest
        securityContext: { privileged: true }
        env: [{ name: NIC, value: "ens5f0" }, { name: QUEUES, value: "0,1" }]
        volumeMounts:
        - { name: bpffs, mountPath: /sys/fs/bpf }
        - { name: modules, mountPath: /lib/modules, readOnly: true }
      volumes:
      - { name: bpffs, hostPath: { path: /sys/fs/bpf, type: DirectoryOrCreate } }
      - { name: modules, hostPath: { path: /lib/modules, type: Directory } }
