# k8s/daemonset-dpdk.yaml
# DaemonSet: DPDK fast path
apiVersion: apps/v1
kind: DaemonSet
metadata: { name: pcf-dpdk, namespace: kube-system }
spec:
  selector: { matchLabels: { app: pcf-dpdk } }
  template:
    metadata: { labels: { app: pcf-dpdk } }
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: dpdk
        image: your-registry/pcf-dpdk:latest
        securityContext: { privileged: true }
        env:
        - { name: NIC, value: "ens5f0" }
        - { name: QUEUES, value: "0,1" }
        - { name: HUGE, value: "1024" }
        resources:
          requests: { cpu: "4", memory: "2Gi", hugepages-2Mi: "1024Mi" }
          limits:   { cpu: "4", memory: "2Gi", hugepages-2Mi: "1024Mi" }
        volumeMounts:
        - { name: hugepages, mountPath: /dev/hugepages }
        - { name: bpffs,     mountPath: /sys/fs/bpf }
      volumes:
      - name: hugepages
        emptyDir: { medium: HugePages }
      - name: bpffs
        hostPath: { path: /sys/fs/bpf, type: DirectoryOrCreate }
